name: Delete Artifacts
on:
  check_suite
jobs:
  build:        
    runs-on: ubuntu-latest
    steps:
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
